spring:
  application:
    name: study

  datasource:
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: shop
    password: 1212
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create  # (??: create, update, validate, none)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false  # ?? ? ?? ???? (?? ? true ??)
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080  # ?? ?? ??
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  level:
    org.hibernate.SQL: debug  # ???? SQL ??
    org.hibernate.orm.jdbc.bind: trace  # SQL ???? ??? ??
    org.hibernate.schema: debug