logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
spring:
  application:
    name: study
  thymeleaf:
    cache: 'false'
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: 'true'
  datasource:
    password: '1111'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3305/shop?useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    database-platform: org.hibernate.dialect.MySQLDialect
  devtools:
    livereload:
      enabled: 'true'
